/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DeptFormPicker: typeof import('./../components/system-select/dept-form-picker.vue')['default']
    DeptSearchPicker: typeof import('./../components/system-select/dept-search-picker.vue')['default']
    DictTag: typeof import('./../components/dict-tag/dict-tag.vue')['default']
    UserFormPicker: typeof import('./../components/system-select/user-form-picker.vue')['default']
    UserPicker: typeof import('./../components/system-select/user-picker.vue')['default']
    UserSearchPicker: typeof import('./../components/system-select/user-search-picker.vue')['default']
    YdFormPicker: typeof import('./../components/yudao-ui/yd-form-picker/yd-form-picker.vue')['default']
    YdSearchDateRange: typeof import('./../components/yudao-ui/yd-search-date-range/yd-search-date-range.vue')['default']
    YdSearchPicker: typeof import('./../components/yudao-ui/yd-search-picker/yd-search-picker.vue')['default']
    YdTreeSelect: typeof import('./../components/yudao-ui/yd-tree-select/yd-tree-select.vue')['default']
    YdUpload: typeof import('./../components/yudao-ui/yd-upload/yd-upload.vue')['default']
    YdUploadFile: typeof import('./../components/yudao-ui/yd-upload-file/yd-upload-file.vue')['default']
    YdUploadImg: typeof import('./../components/yudao-ui/yd-upload-img/yd-upload-img.vue')['default']
    YdUploadImgs: typeof import('./../components/yudao-ui/yd-upload-imgs/yd-upload-imgs.vue')['default']
  }
}
